## Essentiels de Pandas et NumPy

### Pandas

- **Pandas** est une bibliothèque Python pour la manipulation et l’analyse de données tabulaires.
- Les objets principaux sont :
  - **DataFrame** : tableau de données à deux dimensions (lignes et colonnes).
  - **Series** : colonne ou vecteur à une dimension.

**Fonctions clés :**
- `pd.read_csv("fichier.csv")` : lire un fichier CSV.
- `df.head()` : afficher les premières lignes.
- `df.info()` : informations sur le DataFrame.
- `df.describe()` : statistiques descriptives.
- `df["colonne"]` : accéder à une colonne.
- `df.loc[ligne, colonne]` : accès par étiquette.
- `df.iloc[ligne, colonne]` : accès par indice.
- `df.drop()` : supprimer des lignes ou colonnes.
- `df.groupby("colonne")` : regrouper les données.

### NumPy

- **NumPy** est une bibliothèque pour le calcul scientifique et le traitement de tableaux multidimensionnels.
- L’objet principal est :
  - **ndarray** : tableau de nombres à n dimensions.

**Fonctions clés :**
- `np.array([1, 2, 3])` : créer un tableau.
- `np.zeros((2,3))` : tableau de zéros.
- `np.ones((2,3))` : tableau de uns.
- `np.arange(0, 10, 2)` : tableau d’entiers de 0 à 8.
- `np.mean(a)` : moyenne.
- `np.sum(a)` : somme.
- `np.dot(a, b)` : produit matriciel.
- `np.reshape(a, (n, m))` : changer la forme du tableau.

---

**Exemple d’utilisation :**

```python
import pandas as pd
import numpy as np

df = pd.read_csv("donnees.csv")
print(df.head())


## DataFrame et Series avec Pandas

- **DataFrame** :  
  Tableau de données à deux dimensions (lignes et colonnes), similaire à une feuille Excel ou une table SQL.  
  Chaque colonne peut contenir un type de données différent.

  ```python
  import pandas as pd

  # Création d'un DataFrame
  df = pd.DataFrame({
      "nom": ["Alice", "Bob", "Charlie"],
      "age": [25, 35, 30]
  })
  print(df)
  ```

- **Series** :  
  Objet à une dimension, représentant une seule colonne ou un vecteur.

  ```python
  # Création d'une Series
  s = pd.Series([10, 20, 30])
  print(s)

  # Extraire une colonne d'un DataFrame (cela donne une Series)
  ages = df["age"]
  print(ages)
  ```

- **Résumé** :  
  - Un **DataFrame** est une collection de **Series** alignées sur un même index.
  

## Indexation et sélection conditionnée avec la librairie Pandas

### Indexation

- **Accéder à une colonne** :
  ```python
  df["nom_colonne"]
  ```
- **Accéder à une ligne par son index** :
  ```python
  df.loc[3]      # Par étiquette (index)
  df.iloc[3]     # Par position (entier)
  ```
- **Accéder à une cellule** :
  ```python
  df.loc[3, "nom_colonne"]
  df.iloc[3, 2]
  ```

### Sélection conditionnée

- **Filtrer les lignes selon une condition** :
  ```python
  df[df["age"] > 30]           # Lignes où la colonne 'age' > 30
  df[df["ville"] == "Paris"]   # Lignes où la colonne 'ville' vaut 'Paris'
  ```

- **Combiner plusieurs conditions** :
  ```python
  df[(df["age"] > 30) & (df["ville"] == "Paris")]
  df[(df["age"] < 18) | (df["ville"] == "Lyon")]
  ```

- **Sélectionner certaines colonnes après filtrage** :
  ```python
  df[df["age"] > 30][["nom", "age"]]
  ```

---

**Exemple :**

```python
import pandas as pd

df = pd.DataFrame({
    "nom": ["Alice", "Bob", "Charlie"],
    "age": [25, 35, 30],
    "ville": ["Paris", "Lyon", "Paris"]
})

# Sélection des personnes de Paris ayant plus de 28 ans
resultat = df[(df["ville"] == "Paris") & (df["age"] > 28)]

In [7]:
import pandas as pd
car_prices = pd.read_csv('car_prices.csv')
car_prices.head(3)

year make     model        trim   body transmission                vin  \
0  2015  Kia   Sorento          LX    SUV    automatic  5xyktca69fg566472   
1  2015  Kia   Sorento          LX    SUV    automatic  5xyktca69fg561319   
2  2014  BMW  3 Series  328i SULEV  Sedan    automatic  wba3c1c51ek116351   

  state  condition  odometer  color interior  \
0    ca        5.0   16639.0  white    black   
1    ca        5.0    9393.0  white    beige   
2    ca       45.0    1331.0   gray    black   

                                   seller      mmr  sellingprice  \
0                 kia motors america  inc  20500.0       21500.0   
1                 kia motors america  inc  20800.0       21500.0   
2  financial services remarketing (lease)  31900.0       30000.0   

                                  saledate  
0  Tue Dec 16 2014 12:30:00 GMT-0800 (PST)  
1  Tue Dec 16 2014 12:30:00 GMT-0800 (PST)  
2  Thu Jan 15 2015 04:30:00 GMT-0800 (PST)

## Matplotlib

- **Matplotlib** est une bibliothèque Python utilisée pour créer des graphiques et visualiser des données.
- Elle permet de réaliser des courbes, des histogrammes, des diagrammes en barres, des nuages de points, etc.

### Fonctions clés

- `plt.plot(x, y)` : tracer une courbe.
- `plt.bar(x, y)` : diagramme en barres.
- `plt.hist(data)` : histogramme.
- `plt.scatter(x, y)` : nuage de points.
- `plt.title("Titre")` : ajouter un titre.
- `plt.xlabel("Nom axe X")`, `plt.ylabel("Nom axe Y")` : nommer les axes.
- `plt.legend()` : afficher la légende.
- `plt.show()` : afficher le graphique.

### Exemple simple

```python
import matplotlib.pyplot as plt

x = [1, 2, 3, 4]
y = [10, 20, 25, 30]

plt.plot(x, y, label="Courbe")
plt.title("Exemple de graphique")
plt.xlabel("X")
plt.ylabel("Y")
plt.legend()

import matplotlib.pyplot as plt
x = car_prices['year']
y = car_prices['sellingprice'] 
plt.scatter(x, y)
plt.xlabel('Year')
plt.ylabel('Price')
plt.title('Prix des voitures en fonction de l\'année')

x = [1, 2, 3, 4]
y = [10, 20, 25, 30]

plt.plot(x, y, label="Courbe")
plt.title("Exemple de graphique")
plt.xlabel("X")
plt.ylabel("Y")
plt.legend()

In [13]:
students_sociali_media_addiction = pd.read_csv('students_social_media_addiction.csv')
students_sociali_media_addiction.describe()

Student_ID         Age  Avg_Daily_Usage_Hours  Sleep_Hours_Per_Night  \
count  705.000000  705.000000             705.000000             705.000000   
mean   353.000000   20.659574               4.918723               6.868936   
std    203.660256    1.399217               1.257395               1.126848   
min      1.000000   18.000000               1.500000               3.800000   
25%    177.000000   19.000000               4.100000               6.000000   
50%    353.000000   21.000000               4.800000               6.900000   
75%    529.000000   22.000000               5.800000               7.700000   
max    705.000000   24.000000               8.500000               9.600000   

       Mental_Health_Score  Conflicts_Over_Social_Media  Addicted_Score  
count           705.000000                   705.000000      705.000000  
mean              6.226950                     2.849645        6.436879  
std               1.105055                     0.957968        1.587165  
min               4.000000                     0.000000        2.000000  
25%               5.000000                     2.000000        5.000000  
50%               6.000000                     3.000000        7.000000  
75%               7.000000                     4.000000        8.000000  
max               9.000000                     5.000000        9.000000


age_score_counts = students_sociali_media_addiction.groupby(['Addicted_Score', 'Age']).size().unstack(fill_value=0)

# Tracer le graphique en barres empilées
age_score_counts.plot(kind='bar', stacked=True)
plt.xlabel('Addicted Score')
plt.ylabel('Nombre d\'étudiants')
plt.title('Nombre d\'étudiants par âge pour chaque score d\'addiction')
plt.legend(title='Âge')

## Algèbre linéaire : essentiels pour l’analyse de données

L’algèbre linéaire est une branche des mathématiques qui étudie les vecteurs, les matrices et les opérations sur ces objets.  
Elle est fondamentale en analyse de données, machine learning et statistiques.

### Concepts clés

- **Vecteur** :  
  Un vecteur est une liste ordonnée de nombres, par exemple `[2, 5, 7]`.  
  Il peut représenter une observation (ex : les notes d’un élève) ou une variable (ex : les températures sur plusieurs jours).

- **Matrice** :  
  Une matrice est un tableau rectangulaire de nombres (2D array), composé de lignes et de colonnes.  
  Elle permet de stocker plusieurs vecteurs, comme un tableau de données où chaque ligne est une observation et chaque colonne une variable.

- **Opérations sur matrices** :  
  - **Addition** : additionner deux matrices de même taille.
  - **Multiplication** : produit matriciel, utile pour les transformations et les modèles.
  - **Transposition** : inverser lignes et colonnes.
  - **Inversion** : trouver la matrice inverse (utile pour résoudre des systèmes).

- **Système d’équations linéaires** :  
  Résoudre plusieurs équations simultanées, par exemple pour trouver les paramètres d’un modèle.

- **Valeurs propres et vecteurs propres** :  
  Utilisés pour la réduction de dimension (ex : PCA), pour comprendre la structure des données.

- **Norme** :  
  Mesure la “taille” ou la longueur d’un vecteur (distance à l’origine).

### Utilité en analyse de données

- **Stockage des données** :  
  Les données tabulaires sont souvent représentées sous forme de matrices pour faciliter les calculs.

- **Transformation des données** :  
  Les opérations matricielles permettent de manipuler, transformer et combiner les données.

- **Réduction de dimension** :  
  Des techniques comme la PCA (Analyse en Composantes Principales) utilisent l’algèbre linéaire pour simplifier les données et extraire l’essentiel.

- **Modélisation** :  
  Les modèles statistiques et de machine learning utilisent des opérations sur vecteurs et matrices pour l’entraînement et la prédiction.

### Exemple simple en Python avec NumPy

```python
import numpy as np

# Création d’un vecteur
v = np.array([1, 2, 3])

# Création d’une matrice
M = np.array([[1, 2], [3, 4]])

# Addition de matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
addition = A + B

# Multiplication de matrices
resultat = np.dot(M, v[:2])

# Transposition
transposée = M.T

print("Addition :\n", addition)
print("Multiplication :\n", resultat)

In [29]:
import numpy as np
v = np.array([1, 2, 3])

# Création d’une matrice
M = np.array([[1, 2], [3, 4]])

# Addition de matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
addition = A + B

# Multiplication de matrices
resultat = np.dot(A,B)

# Transposition
transposée = M.T
print("all",v[:2])

print("Addition :\n", addition)
print("Multiplication :\n", resultat)
print("Transposée :\n", transposée)

all [1 2]
Addition :
 [[ 6  8]
 [10 12]]
Multiplication :
 [[19 22]
 [43 50]]
Transposée :
 [[1 3]
 [2 4]]
